"""baseline schema

Revision ID: 0805015d119c
Revises: 
Create Date: 2026-06-13 18:53:20.917198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '0805015d119c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_uid', sa.String(length=64), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('price_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assinaturas_status'), 'assinaturas', ['status'], unique=False)
    op.create_index(op.f('ix_assinaturas_stripe_customer_id'), 'assinaturas', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_assinaturas_stripe_subscription_id'), 'assinaturas', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_assinaturas_usuario_uid'), 'assinaturas', ['usuario_uid'], unique=False)
    op.create_table('bancas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_externo', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('sigla', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bancas_id_externo'), 'bancas', ['id_externo'], unique=True)
    op.create_index(op.f('ix_bancas_nome'), 'bancas', ['nome'], unique=True)
    op.create_index(op.f('ix_bancas_slug'), 'bancas', ['slug'], unique=True)
    op.create_table('cadernos_questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_uid', sa.String(length=64), nullable=True),
    sa.Column('nome', sa.String(length=512), nullable=False),
    sa.Column('pasta', sa.String(length=256), nullable=True),
    sa.Column('filtros', sa.JSON(), nullable=True),
    sa.Column('question_ids', sa.JSON(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('tc_caderno_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cadernos_questoes_owner_uid'), 'cadernos_questoes', ['owner_uid'], unique=False)
    op.create_index(op.f('ix_cadernos_questoes_tc_caderno_id'), 'cadernos_questoes', ['tc_caderno_id'], unique=True)
    op.create_table('calculadora_historico',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_uid', sa.String(length=64), nullable=True),
    sa.Column('caderno_id', sa.Integer(), nullable=True),
    sa.Column('questao_id', sa.BigInteger(), nullable=True),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculadora_historico_caderno_id'), 'calculadora_historico', ['caderno_id'], unique=False)
    op.create_index(op.f('ix_calculadora_historico_created_at'), 'calculadora_historico', ['created_at'], unique=False)
    op.create_index(op.f('ix_calculadora_historico_questao_id'), 'calculadora_historico', ['questao_id'], unique=False)
    op.create_index(op.f('ix_calculadora_historico_usuario_id'), 'calculadora_historico', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_calculadora_historico_usuario_uid'), 'calculadora_historico', ['usuario_uid'], unique=False)
    op.create_table('concursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('arquivo_nome', sa.String(length=256), nullable=True),
    sa.Column('total_candidatos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('icon_color', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_slug'), 'decks', ['slug'], unique=True)
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=False),
    sa.Column('icon_color', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplinas_slug'), 'disciplinas', ['slug'], unique=True)
    op.create_table('guias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tc_guia_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('nome', sa.String(length=512), nullable=False),
    sa.Column('banca', sa.String(length=128), nullable=True),
    sa.Column('tc_pasta_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_cadernos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guias_tc_guia_id'), 'guias', ['tc_guia_id'], unique=True)
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_externo', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['materias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materias_id_externo'), 'materias', ['id_externo'], unique=True)
    op.create_index(op.f('ix_materias_nome'), 'materias', ['nome'], unique=True)
    op.create_table('orgaos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_externo', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=False),
    sa.Column('sigla', sa.String(length=64), nullable=True),
    sa.Column('esfera', sa.String(length=32), nullable=True),
    sa.Column('regiao', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orgaos_id_externo'), 'orgaos', ['id_externo'], unique=True)
    op.create_index(op.f('ix_orgaos_nome'), 'orgaos', ['nome'], unique=False)
    op.create_index(op.f('ix_orgaos_slug'), 'orgaos', ['slug'], unique=True)
    op.create_table('assuntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_externo', sa.Integer(), nullable=True),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('materia_id', 'nome', name='uq_assunto_materia_nome')
    )
    op.create_index(op.f('ix_assuntos_id_externo'), 'assuntos', ['id_externo'], unique=True)
    op.create_index(op.f('ix_assuntos_materia_id'), 'assuntos', ['materia_id'], unique=False)
    op.create_index(op.f('ix_assuntos_nome'), 'assuntos', ['nome'], unique=False)
    op.create_table('aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=512), nullable=False),
    sa.Column('pdf_path_minio', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('texto_completo', sa.Text(), nullable=True),
    sa.Column('modelo_usado', sa.String(length=128), nullable=True),
    sa.Column('erro_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cadernos_salvos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_uid', sa.String(length=64), nullable=False),
    sa.Column('caderno_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caderno_id'], ['cadernos_questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_uid', 'caderno_id', name='uq_caderno_salvo')
    )
    op.create_index(op.f('ix_cadernos_salvos_caderno_id'), 'cadernos_salvos', ['caderno_id'], unique=False)
    op.create_index(op.f('ix_cadernos_salvos_usuario_uid'), 'cadernos_salvos', ['usuario_uid'], unique=False)
    op.create_table('candidatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concurso_id', sa.Integer(), nullable=False),
    sa.Column('inscricao', sa.String(length=64), nullable=False),
    sa.Column('cargo', sa.String(length=256), nullable=False),
    sa.Column('polo', sa.String(length=32), nullable=False),
    sa.Column('macropolo', sa.String(length=64), nullable=False),
    sa.Column('nascimento', sa.String(length=16), nullable=True),
    sa.Column('pontos', sa.Float(), nullable=False),
    sa.Column('discursiva', sa.Float(), nullable=False),
    sa.Column('tot_esp', sa.Float(), nullable=False),
    sa.Column('tot_bas', sa.Float(), nullable=False),
    sa.Column('l_port', sa.Float(), nullable=False),
    sa.Column('l_ing', sa.Float(), nullable=False),
    sa.Column('situacao', sa.String(length=128), nullable=True),
    sa.Column('pos_ac', sa.Integer(), nullable=True),
    sa.Column('pos_pcd', sa.Integer(), nullable=True),
    sa.Column('pos_pn', sa.Integer(), nullable=True),
    sa.Column('pos_pi', sa.Integer(), nullable=True),
    sa.Column('pos_pq', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concurso_id'], ['concursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidatos_concurso_id'), 'candidatos', ['concurso_id'], unique=False)
    op.create_index(op.f('ix_candidatos_pontos'), 'candidatos', ['pontos'], unique=False)
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_externo', sa.Integer(), nullable=True),
    sa.Column('orgao_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('escolaridade', sa.Text(), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargos_ano'), 'cargos', ['ano'], unique=False)
    op.create_index(op.f('ix_cargos_id_externo'), 'cargos', ['id_externo'], unique=True)
    op.create_index(op.f('ix_cargos_nome'), 'cargos', ['nome'], unique=False)
    op.create_index(op.f('ix_cargos_orgao_id'), 'cargos', ['orgao_id'], unique=False)
    op.create_table('guia_cadernos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guia_id', sa.Integer(), nullable=False),
    sa.Column('tc_caderno_id', sa.BigInteger(), nullable=False),
    sa.Column('tc_caderno_base', sa.BigInteger(), nullable=True),
    sa.Column('nome', sa.String(length=512), nullable=False),
    sa.Column('disciplina', sa.String(length=512), nullable=True),
    sa.Column('total_questoes', sa.Integer(), nullable=False),
    sa.Column('total_capitulos', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('caderno_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caderno_id'], ['cadernos_questoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guia_id'], ['guias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guia_id', 'tc_caderno_id', name='uq_guia_caderno')
    )
    op.create_index(op.f('ix_guia_cadernos_guia_id'), 'guia_cadernos', ['guia_id'], unique=False)
    op.create_index(op.f('ix_guia_cadernos_tc_caderno_id'), 'guia_cadernos', ['tc_caderno_id'], unique=False)
    op.create_table('blocos_conteudo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('paginas', sa.String(length=32), nullable=False),
    sa.Column('resumo_markdown', sa.Text(), nullable=True),
    sa.Column('formulas_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('assunto', sa.String(length=256), nullable=False),
    sa.Column('frente', sa.Text(), nullable=False),
    sa.Column('verso', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=True),
    sa.Column('proxima_revisao', sa.DateTime(), nullable=True),
    sa.Column('fator_facilidade', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_externo', sa.Integer(), nullable=True),
    sa.Column('banca_id', sa.Integer(), nullable=True),
    sa.Column('orgao_id', sa.Integer(), nullable=True),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=64), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('data_aplicacao', sa.Date(), nullable=True),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banca_id'], ['bancas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provas_ano'), 'provas', ['ano'], unique=False)
    op.create_index(op.f('ix_provas_banca_id'), 'provas', ['banca_id'], unique=False)
    op.create_index(op.f('ix_provas_cargo_id'), 'provas', ['cargo_id'], unique=False)
    op.create_index(op.f('ix_provas_id_externo'), 'provas', ['id_externo'], unique=True)
    op.create_index(op.f('ix_provas_orgao_id'), 'provas', ['orgao_id'], unique=False)
    op.create_table('questoes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_externo', sa.BigInteger(), nullable=True),
    sa.Column('codigo_externo', sa.String(length=64), nullable=True),
    sa.Column('prova_id', sa.Integer(), nullable=True),
    sa.Column('banca_id', sa.Integer(), nullable=True),
    sa.Column('orgao_id', sa.Integer(), nullable=True),
    sa.Column('cargo_id', sa.Integer(), nullable=True),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.Column('numero_na_prova', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=64), nullable=True),
    sa.Column('enunciado_md', sa.Text(), nullable=True),
    sa.Column('enunciado_html', sa.Text(), nullable=True),
    sa.Column('gabarito', sa.String(length=64), nullable=True),
    sa.Column('texto_associado', sa.Text(), nullable=True),
    sa.Column('imagens', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banca_id'], ['bancas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prova_id'], ['provas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questoes_banca_id'), 'questoes', ['banca_id'], unique=False)
    op.create_index(op.f('ix_questoes_cargo_id'), 'questoes', ['cargo_id'], unique=False)
    op.create_index(op.f('ix_questoes_codigo_externo'), 'questoes', ['codigo_externo'], unique=True)
    op.create_index(op.f('ix_questoes_id_externo'), 'questoes', ['id_externo'], unique=True)
    op.create_index(op.f('ix_questoes_materia_id'), 'questoes', ['materia_id'], unique=False)
    op.create_index(op.f('ix_questoes_orgao_id'), 'questoes', ['orgao_id'], unique=False)
    op.create_index(op.f('ix_questoes_prova_id'), 'questoes', ['prova_id'], unique=False)
    op.create_index(op.f('ix_questoes_status'), 'questoes', ['status'], unique=False)
    op.create_index(op.f('ix_questoes_tipo'), 'questoes', ['tipo'], unique=False)
    op.create_table('alternativas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_externo', sa.BigInteger(), nullable=True),
    sa.Column('questao_id', sa.BigInteger(), nullable=False),
    sa.Column('letra', sa.String(length=2), nullable=True),
    sa.Column('texto_md', sa.Text(), nullable=True),
    sa.Column('texto_html', sa.Text(), nullable=True),
    sa.Column('correta', sa.Boolean(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alternativas_id_externo'), 'alternativas', ['id_externo'], unique=True)
    op.create_index(op.f('ix_alternativas_questao_id'), 'alternativas', ['questao_id'], unique=False)
    op.create_table('questao_anotacoes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_uid', sa.String(length=64), nullable=True),
    sa.Column('caderno_id', sa.Integer(), nullable=True),
    sa.Column('questao_id', sa.BigInteger(), nullable=False),
    sa.Column('canvas_json', sa.JSON(), nullable=False),
    sa.Column('strikes_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caderno_id'], ['cadernos_questoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questao_anotacoes_caderno_id'), 'questao_anotacoes', ['caderno_id'], unique=False)
    op.create_index(op.f('ix_questao_anotacoes_questao_id'), 'questao_anotacoes', ['questao_id'], unique=False)
    op.create_index(op.f('ix_questao_anotacoes_usuario_id'), 'questao_anotacoes', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_questao_anotacoes_usuario_uid'), 'questao_anotacoes', ['usuario_uid'], unique=False)
    op.create_index('uq_questao_anotacoes_scope_uid', 'questao_anotacoes', [sa.literal_column("coalesce(usuario_uid, '')"), sa.literal_column('coalesce(caderno_id, 0)'), 'questao_id'], unique=True)
    op.create_table('questao_assunto',
    sa.Column('questao_id', sa.BigInteger(), nullable=False),
    sa.Column('assunto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assunto_id'], ['assuntos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('questao_id', 'assunto_id')
    )
    op.create_table('questao_comentarios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('questao_id', sa.BigInteger(), nullable=False),
    sa.Column('tc_comentario_id', sa.BigInteger(), nullable=True),
    sa.Column('tc_parent_id', sa.BigInteger(), nullable=True),
    sa.Column('autor_nome', sa.String(length=256), nullable=True),
    sa.Column('autor_tipo', sa.String(length=32), nullable=True),
    sa.Column('texto_html', sa.Text(), nullable=True),
    sa.Column('texto_md', sa.Text(), nullable=True),
    sa.Column('curtidas', sa.Integer(), nullable=False),
    sa.Column('publicado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questao_comentarios_questao_id'), 'questao_comentarios', ['questao_id'], unique=False)
    op.create_index(op.f('ix_questao_comentarios_tc_comentario_id'), 'questao_comentarios', ['tc_comentario_id'], unique=True)
    op.create_index(op.f('ix_questao_comentarios_tc_parent_id'), 'questao_comentarios', ['tc_parent_id'], unique=False)
    op.create_table('questao_estatisticas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.BigInteger(), nullable=False),
    sa.Column('total_resolucoes', sa.Integer(), nullable=False),
    sa.Column('total_acertos', sa.Integer(), nullable=False),
    sa.Column('percentual_acertos', sa.Float(), nullable=True),
    sa.Column('distribuicao_json', sa.JSON(), nullable=True),
    sa.Column('fonte', sa.String(length=16), nullable=False),
    sa.Column('coletado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questao_estatisticas_questao_id'), 'questao_estatisticas', ['questao_id'], unique=True)
    op.create_table('questoes_favoritas',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('questao_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_uid', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_uid', 'questao_id', name='uq_favorita_owner_questao')
    )
    op.create_index(op.f('ix_questoes_favoritas_owner_uid'), 'questoes_favoritas', ['owner_uid'], unique=False)
    op.create_index(op.f('ix_questoes_favoritas_questao_id'), 'questoes_favoritas', ['questao_id'], unique=False)
    op.create_table('resolucoes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('questao_id', sa.BigInteger(), nullable=False),
    sa.Column('caderno_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_uid', sa.String(length=64), nullable=True),
    sa.Column('resposta', sa.String(length=16), nullable=True),
    sa.Column('acertou', sa.Boolean(), nullable=True),
    sa.Column('tempo_segundos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caderno_id'], ['cadernos_questoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolucoes_caderno_id'), 'resolucoes', ['caderno_id'], unique=False)
    op.create_index(op.f('ix_resolucoes_created_at'), 'resolucoes', ['created_at'], unique=False)
    op.create_index(op.f('ix_resolucoes_questao_id'), 'resolucoes', ['questao_id'], unique=False)
    op.create_index(op.f('ix_resolucoes_usuario_id'), 'resolucoes', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_resolucoes_usuario_uid'), 'resolucoes', ['usuario_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resolucoes_usuario_uid'), table_name='resolucoes')
    op.drop_index(op.f('ix_resolucoes_usuario_id'), table_name='resolucoes')
    op.drop_index(op.f('ix_resolucoes_questao_id'), table_name='resolucoes')
    op.drop_index(op.f('ix_resolucoes_created_at'), table_name='resolucoes')
    op.drop_index(op.f('ix_resolucoes_caderno_id'), table_name='resolucoes')
    op.drop_table('resolucoes')
    op.drop_index(op.f('ix_questoes_favoritas_questao_id'), table_name='questoes_favoritas')
    op.drop_index(op.f('ix_questoes_favoritas_owner_uid'), table_name='questoes_favoritas')
    op.drop_table('questoes_favoritas')
    op.drop_index(op.f('ix_questao_estatisticas_questao_id'), table_name='questao_estatisticas')
    op.drop_table('questao_estatisticas')
    op.drop_index(op.f('ix_questao_comentarios_tc_parent_id'), table_name='questao_comentarios')
    op.drop_index(op.f('ix_questao_comentarios_tc_comentario_id'), table_name='questao_comentarios')
    op.drop_index(op.f('ix_questao_comentarios_questao_id'), table_name='questao_comentarios')
    op.drop_table('questao_comentarios')
    op.drop_table('questao_assunto')
    op.drop_index('uq_questao_anotacoes_scope_uid', table_name='questao_anotacoes')
    op.drop_index(op.f('ix_questao_anotacoes_usuario_uid'), table_name='questao_anotacoes')
    op.drop_index(op.f('ix_questao_anotacoes_usuario_id'), table_name='questao_anotacoes')
    op.drop_index(op.f('ix_questao_anotacoes_questao_id'), table_name='questao_anotacoes')
    op.drop_index(op.f('ix_questao_anotacoes_caderno_id'), table_name='questao_anotacoes')
    op.drop_table('questao_anotacoes')
    op.drop_index(op.f('ix_alternativas_questao_id'), table_name='alternativas')
    op.drop_index(op.f('ix_alternativas_id_externo'), table_name='alternativas')
    op.drop_table('alternativas')
    op.drop_index(op.f('ix_questoes_tipo'), table_name='questoes')
    op.drop_index(op.f('ix_questoes_status'), table_name='questoes')
    op.drop_index(op.f('ix_questoes_prova_id'), table_name='questoes')
    op.drop_index(op.f('ix_questoes_orgao_id'), table_name='questoes')
    op.drop_index(op.f('ix_questoes_materia_id'), table_name='questoes')
    op.drop_index(op.f('ix_questoes_id_externo'), table_name='questoes')
    op.drop_index(op.f('ix_questoes_codigo_externo'), table_name='questoes')
    op.drop_index(op.f('ix_questoes_cargo_id'), table_name='questoes')
    op.drop_index(op.f('ix_questoes_banca_id'), table_name='questoes')
    op.drop_table('questoes')
    op.drop_index(op.f('ix_provas_orgao_id'), table_name='provas')
    op.drop_index(op.f('ix_provas_id_externo'), table_name='provas')
    op.drop_index(op.f('ix_provas_cargo_id'), table_name='provas')
    op.drop_index(op.f('ix_provas_banca_id'), table_name='provas')
    op.drop_index(op.f('ix_provas_ano'), table_name='provas')
    op.drop_table('provas')
    op.drop_table('flashcards')
    op.drop_table('blocos_conteudo')
    op.drop_index(op.f('ix_guia_cadernos_tc_caderno_id'), table_name='guia_cadernos')
    op.drop_index(op.f('ix_guia_cadernos_guia_id'), table_name='guia_cadernos')
    op.drop_table('guia_cadernos')
    op.drop_index(op.f('ix_cargos_orgao_id'), table_name='cargos')
    op.drop_index(op.f('ix_cargos_nome'), table_name='cargos')
    op.drop_index(op.f('ix_cargos_id_externo'), table_name='cargos')
    op.drop_index(op.f('ix_cargos_ano'), table_name='cargos')
    op.drop_table('cargos')
    op.drop_index(op.f('ix_candidatos_pontos'), table_name='candidatos')
    op.drop_index(op.f('ix_candidatos_concurso_id'), table_name='candidatos')
    op.drop_table('candidatos')
    op.drop_index(op.f('ix_cadernos_salvos_usuario_uid'), table_name='cadernos_salvos')
    op.drop_index(op.f('ix_cadernos_salvos_caderno_id'), table_name='cadernos_salvos')
    op.drop_table('cadernos_salvos')
    op.drop_table('aulas')
    op.drop_index(op.f('ix_assuntos_nome'), table_name='assuntos')
    op.drop_index(op.f('ix_assuntos_materia_id'), table_name='assuntos')
    op.drop_index(op.f('ix_assuntos_id_externo'), table_name='assuntos')
    op.drop_table('assuntos')
    op.drop_index(op.f('ix_orgaos_slug'), table_name='orgaos')
    op.drop_index(op.f('ix_orgaos_nome'), table_name='orgaos')
    op.drop_index(op.f('ix_orgaos_id_externo'), table_name='orgaos')
    op.drop_table('orgaos')
    op.drop_index(op.f('ix_materias_nome'), table_name='materias')
    op.drop_index(op.f('ix_materias_id_externo'), table_name='materias')
    op.drop_table('materias')
    op.drop_index(op.f('ix_guias_tc_guia_id'), table_name='guias')
    op.drop_table('guias')
    op.drop_index(op.f('ix_disciplinas_slug'), table_name='disciplinas')
    op.drop_table('disciplinas')
    op.drop_index(op.f('ix_decks_slug'), table_name='decks')
    op.drop_table('decks')
    op.drop_table('concursos')
    op.drop_index(op.f('ix_calculadora_historico_usuario_uid'), table_name='calculadora_historico')
    op.drop_index(op.f('ix_calculadora_historico_usuario_id'), table_name='calculadora_historico')
    op.drop_index(op.f('ix_calculadora_historico_questao_id'), table_name='calculadora_historico')
    op.drop_index(op.f('ix_calculadora_historico_created_at'), table_name='calculadora_historico')
    op.drop_index(op.f('ix_calculadora_historico_caderno_id'), table_name='calculadora_historico')
    op.drop_table('calculadora_historico')
    op.drop_index(op.f('ix_cadernos_questoes_tc_caderno_id'), table_name='cadernos_questoes')
    op.drop_index(op.f('ix_cadernos_questoes_owner_uid'), table_name='cadernos_questoes')
    op.drop_table('cadernos_questoes')
    op.drop_index(op.f('ix_bancas_slug'), table_name='bancas')
    op.drop_index(op.f('ix_bancas_nome'), table_name='bancas')
    op.drop_index(op.f('ix_bancas_id_externo'), table_name='bancas')
    op.drop_table('bancas')
    op.drop_index(op.f('ix_assinaturas_usuario_uid'), table_name='assinaturas')
    op.drop_index(op.f('ix_assinaturas_stripe_subscription_id'), table_name='assinaturas')
    op.drop_index(op.f('ix_assinaturas_stripe_customer_id'), table_name='assinaturas')
    op.drop_index(op.f('ix_assinaturas_status'), table_name='assinaturas')
    op.drop_table('assinaturas')
    # ### end Alembic commands ###
